/********************************************************************
* GmpFppDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error GmpFppDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableGmpFppDict();
extern void G__cpp_setup_inheritanceGmpFppDict();
extern void G__cpp_setup_typetableGmpFppDict();
extern void G__cpp_setup_memvarGmpFppDict();
extern void G__cpp_setup_globalGmpFppDict();
extern void G__cpp_setup_memfuncGmpFppDict();
extern void G__cpp_setup_funcGmpFppDict();
extern void G__set_cpp_environmentGmpFppDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "GmpStrawChamber.h"
#include "GmpFppChamber.h"
#include "GmpFppPlane.h"
#include "GmpFppCluster.h"
#include "GmpFppHit.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__GmpFppDictLN_TClass;
extern G__linked_taginfo G__GmpFppDictLN_TBuffer;
extern G__linked_taginfo G__GmpFppDictLN_TMemberInspector;
extern G__linked_taginfo G__GmpFppDictLN_TObject;
extern G__linked_taginfo G__GmpFppDictLN_TNamed;
extern G__linked_taginfo G__GmpFppDictLN_vectorlEdoublecOallocatorlEdoublegRsPgR;
extern G__linked_taginfo G__GmpFppDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__GmpFppDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__GmpFppDictLN_TClonesArray;
extern G__linked_taginfo G__GmpFppDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__GmpFppDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__GmpFppDictLN_TDatime;
extern G__linked_taginfo G__GmpFppDictLN_THaEvData;
extern G__linked_taginfo G__GmpFppDictLN_TVector3;
extern G__linked_taginfo G__GmpFppDictLN_THaAnalysisObject;
extern G__linked_taginfo G__GmpFppDictLN_THaAnalysisObjectcLcLEStatus;
extern G__linked_taginfo G__GmpFppDictLN_THaAnalysisObjectcLcLEMode;
extern G__linked_taginfo G__GmpFppDictLN_vectorlEstringcOallocatorlEstringgRsPgR;
extern G__linked_taginfo G__GmpFppDictLN_reverse_iteratorlEvectorlEstringcOallocatorlEstringgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__GmpFppDictLN_TMatrixTBaselEfloatgR;
extern G__linked_taginfo G__GmpFppDictLN_TMatrixTBaselEdoublegR;
extern G__linked_taginfo G__GmpFppDictLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__GmpFppDictLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__GmpFppDictLN_TElementActionTlEfloatgR;
extern G__linked_taginfo G__GmpFppDictLN_TElementPosActionTlEfloatgR;
extern G__linked_taginfo G__GmpFppDictLN_TMatrixTlEfloatgR;
extern G__linked_taginfo G__GmpFppDictLN_TMatrixTRow_constlEfloatgR;
extern G__linked_taginfo G__GmpFppDictLN_TMatrixTRowlEfloatgR;
extern G__linked_taginfo G__GmpFppDictLN_TMatrixTDiag_constlEfloatgR;
extern G__linked_taginfo G__GmpFppDictLN_TMatrixTColumn_constlEfloatgR;
extern G__linked_taginfo G__GmpFppDictLN_TMatrixTFlat_constlEfloatgR;
extern G__linked_taginfo G__GmpFppDictLN_TMatrixTSub_constlEfloatgR;
extern G__linked_taginfo G__GmpFppDictLN_TMatrixTSparseRow_constlEfloatgR;
extern G__linked_taginfo G__GmpFppDictLN_TMatrixTSparseDiag_constlEfloatgR;
extern G__linked_taginfo G__GmpFppDictLN_TMatrixTColumnlEfloatgR;
extern G__linked_taginfo G__GmpFppDictLN_TMatrixTDiaglEfloatgR;
extern G__linked_taginfo G__GmpFppDictLN_TMatrixTFlatlEfloatgR;
extern G__linked_taginfo G__GmpFppDictLN_TMatrixTSublEfloatgR;
extern G__linked_taginfo G__GmpFppDictLN_TMatrixTSparseRowlEfloatgR;
extern G__linked_taginfo G__GmpFppDictLN_TMatrixTSparseDiaglEfloatgR;
extern G__linked_taginfo G__GmpFppDictLN_THaDetectorBase;
extern G__linked_taginfo G__GmpFppDictLN_vectorlEintcOallocatorlEintgRsPgR;
extern G__linked_taginfo G__GmpFppDictLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__GmpFppDictLN_THaDetector;
extern G__linked_taginfo G__GmpFppDictLN_THaApparatus;
extern G__linked_taginfo G__GmpFppDictLN_THaSpectrometerDetector;
extern G__linked_taginfo G__GmpFppDictLN_THaNonTrackingDetector;
extern G__linked_taginfo G__GmpFppDictLN_GmpFppChamber;
extern G__linked_taginfo G__GmpFppDictLN_GmpStrawChamber;
extern G__linked_taginfo G__GmpFppDictLN_THaSubDetector;
extern G__linked_taginfo G__GmpFppDictLN_GmpFppPlane;
extern G__linked_taginfo G__GmpFppDictLN_GmpFppHit;
extern G__linked_taginfo G__GmpFppDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__GmpFppDictLN_vectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgR;
extern G__linked_taginfo G__GmpFppDictLN_reverse_iteratorlEvectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__GmpFppDictLN_GmpFppPlanecLcLETDCPairStatus;
extern G__linked_taginfo G__GmpFppDictLN_GmpFppCluster;
extern G__linked_taginfo G__GmpFppDictLN_vectorlEGmpFppHitmUcOallocatorlEGmpFppHitmUgRsPgR;
extern G__linked_taginfo G__GmpFppDictLN_reverse_iteratorlEvectorlEGmpFppHitmUcOallocatorlEGmpFppHitmUgRsPgRcLcLiteratorgR;

/* STUB derived class for protected member access */
